@extends('layouts.app')

@section('title', 'شجرة العائلة - ' . $family->name)

@section('content')
<div class="family-tree-container">
    <div class="text-center mb-4">
        <h2 class="text-primary">
            <i class="fas fa-sitemap me-2"></i>
            شجرة عائلة {{ $family->name }}
        </h2>
        @if($family->description)
            <p class="text-muted">{{ $family->description }}</p>
        @endif
    </div>
    
    @if($members->count() > 0)
        <!-- Tree SVG Container -->
        <div id="family-tree" class="text-center">
            <svg id="tree-svg" width="100%" height="600" style="border: 2px solid #e9ecef; border-radius: 15px; background: white;">
                <!-- SVG content will be generated by JavaScript -->
            </svg>
        </div>
        
        <!-- Tree Controls -->
        <div class="text-center mt-4">
            <button class="btn btn-primary me-2" onclick="zoomIn()">
                <i class="fas fa-search-plus me-1"></i>
                تكبير
            </button>
            <button class="btn btn-primary me-2" onclick="zoomOut()">
                <i class="fas fa-search-minus me-1"></i>
                تصغير
            </button>
            <button class="btn btn-success me-2" onclick="resetZoom()">
                <i class="fas fa-expand-arrows-alt me-1"></i>
                إعادة تعيين
            </button>
            <button class="btn btn-warning" onclick="downloadTree()">
                <i class="fas fa-download me-1"></i>
                تحميل الصورة
            </button>
        </div>
        
        <!-- Members Legend -->
        <div class="row mt-5">
            @foreach($members->groupBy('generation') as $generation => $generationMembers)
            <div class="col-md-6 col-lg-4 mb-3">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h6 class="mb-0">الجيل {{ $generation }}</h6>
                    </div>
                    <div class="card-body">
                        @foreach($generationMembers as $member)
                        <div class="d-flex align-items-center mb-2">
                            <div class="member-avatar generation-{{ $member->generation }}">
                                @if($member->gender === 'male')
                                    <i class="fas fa-male"></i>
                                @else
                                    <i class="fas fa-female"></i>
                                @endif
                            </div>
                            <div class="ms-3">
                                <div class="fw-bold">{{ $member->getDisplayName() }}</div>
                                @if($member->relationship)
                                    <small class="text-muted">{{ $member->relationship }}</small>
                                @endif
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    @else
        <div class="text-center py-5">
            <i class="fas fa-sitemap fa-5x text-muted mb-4"></i>
            <h4 class="text-muted">لا توجد أعضاء في العائلة بعد</h4>
            <p class="text-muted">ابدأ بإضافة أعضاء العائلة لرؤية الشجرة</p>
            <a href="{{ route('family.member.create', $family->id) }}" class="btn btn-primary">
                <i class="fas fa-plus me-2"></i>
                إضافة عضو جديد
            </a>
        </div>
    @endif
</div>

<!-- Back to Dashboard -->
<div class="text-center mt-4">
    <a href="{{ route('family.dashboard', $family->id) }}" class="btn btn-outline-primary">
        <i class="fas fa-arrow-right me-2"></i>
        العودة للداش بورد
    </a>
</div>
@endsection

@push('styles')
<style>
.member-avatar {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 16px;
}

.tree-node {
    cursor: pointer;
    transition: all 0.3s ease;
}

.tree-node:hover {
    transform: scale(1.1);
}

.tree-line {
    stroke: #667eea;
    stroke-width: 3;
    fill: none;
}

.member-card-svg {
    fill: #667eea;
    stroke: white;
    stroke-width: 2;
    rx: 10;
    ry: 10;
}

.member-text {
    fill: white;
    font-family: 'Cairo', sans-serif;
    font-size: 12px;
    text-anchor: middle;
    dominant-baseline: central;
}
</style>
@endpush

@push('scripts')
<script>
let members = @json($members);
let currentZoom = 1;

function generateTree() {
    const svg = document.getElementById('tree-svg');
    const width = svg.clientWidth;
    const height = svg.clientHeight;
    
    // Clear previous content
    svg.innerHTML = '';
    
    // Group members by generation
    const generations = {};
    members.forEach(member => {
        if (!generations[member.generation]) {
            generations[member.generation] = [];
        }
        generations[member.generation].push(member);
    });
    
    const generationCount = Object.keys(generations).length;
    const generationHeight = height / (generationCount + 1);
    
    // Generate tree nodes
    Object.keys(generations).forEach(generation => {
        const genMembers = generations[generation];
        const memberWidth = width / genMembers.length;
        
        genMembers.forEach((member, index) => {
            const x = memberWidth * index + memberWidth / 2;
            const y = generationHeight * parseInt(generation);
            
            // Create member rectangle
            const rect = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
            rect.setAttribute('x', x - 60);
            rect.setAttribute('y', y - 25);
            rect.setAttribute('width', 120);
            rect.setAttribute('height', 50);
            rect.setAttribute('class', 'member-card-svg');
            rect.setAttribute('fill', getGenerationColor(member.generation));
            rect.setAttribute('rx', 10);
            rect.setAttribute('ry', 10);
            rect.setAttribute('stroke', 'white');
            rect.setAttribute('stroke-width', 2);
            
            // Create member name text
            const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            text.setAttribute('x', x);
            text.setAttribute('y', y);
            text.setAttribute('class', 'member-text');
            text.setAttribute('font-size', '11');
            text.setAttribute('font-weight', 'bold');
            text.textContent = member.display_name || member.name;
            
            // Create gender icon
            const icon = document.createElementNS('http://www.w3.org/2000/svg', 'text');
            icon.setAttribute('x', x - 50);
            icon.setAttribute('y', y);
            icon.setAttribute('class', 'member-text');
            icon.setAttribute('font-size', '10');
            icon.textContent = member.gender === 'male' ? '♂' : '♀';
            
            svg.appendChild(rect);
            svg.appendChild(text);
            svg.appendChild(icon);
            
            // Draw connections to parents
            if (member.father_id || member.mother_id) {
                const parentY = generationHeight * (parseInt(generation) - 1);
                
                if (member.father_id) {
                    const fatherIndex = generations[member.generation - 1]?.findIndex(p => p.id === member.father_id);
                    if (fatherIndex !== undefined && fatherIndex !== -1) {
                        const parentX = (width / generations[member.generation - 1].length) * fatherIndex + 
                                       (width / generations[member.generation - 1].length) / 2;
                        drawLine(parentX, parentY + 25, x, y - 25);
                    }
                }
            }
        });
    });
}

function drawLine(x1, y1, x2, y2) {
    const svg = document.getElementById('tree-svg');
    const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
    line.setAttribute('x1', x1);
    line.setAttribute('y1', y1);
    line.setAttribute('x2', x2);
    line.setAttribute('y2', y2);
    line.setAttribute('class', 'tree-line');
    svg.appendChild(line);
}

function getGenerationColor(generation) {
    const colors = {
        1: '#667eea',
        2: '#11998e',
        3: '#f093fb',
        4: '#ff416c',
        5: '#ff9a9e'
    };
    return colors[generation] || '#6c757d';
}

function zoomIn() {
    currentZoom += 0.2;
    applyZoom();
}

function zoomOut() {
    currentZoom = Math.max(0.5, currentZoom - 0.2);
    applyZoom();
}

function resetZoom() {
    currentZoom = 1;
    applyZoom();
}

function applyZoom() {
    const svg = document.getElementById('tree-svg');
    svg.style.transform = `scale(${currentZoom})`;
    svg.style.transformOrigin = 'center center';
}

function downloadTree() {
    const svg = document.getElementById('tree-svg');
    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    const img = new Image();
    
    canvas.width = svg.clientWidth;
    canvas.height = svg.clientHeight;
    
    img.onload = function() {
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(img, 0, 0);
        
        const link = document.createElement('a');
        link.download = 'شجرة_عائلة_{{ $family->name }}.png';
        link.href = canvas.toDataURL();
        link.click();
    };
    
    img.src = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(svgData)));
}

// Initialize tree on page load
document.addEventListener('DOMContentLoaded', function() {
    generateTree();
});

// Regenerate tree on window resize
window.addEventListener('resize', function() {
    setTimeout(generateTree, 100);
});
</script>
@endpush
